[package]
name = "baokeshed"
version = "0.1.0"
authors = ["Jack O'Connor <oconnor663@gmail.com>"]
edition = "2018"

[dependencies]
arrayref = "0.3.5"
arrayvec = { version = "0.4.11", default-features = false }
bitflags = "1.1.0"
constant_time_eq = "0.1.4"
