name: tests

on: [push]

jobs:
  test:
    name: Rust ${{ matrix.rust_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_version: [stable, beta, nightly]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust_version }}
        override: true
    # We want to see C compiler flags in the build output, which requires
    # building at high verbosity. To avoid seeing a flood of output, do an
    # initial no-C test runs at low verbosity.
    - run: cargo test
    - run: cargo test --no-default-features
    - run: cargo test -vv --features=c_portable
    - run: cargo test -vv --features=c_sse41
    # The GitHub Actions test machines don't support AVX512 yet (and the macOS
    # ones don't support AVX2), but we should be able to build them.
    - run: cargo build --tests -vv --features=c_avx2
    - run: cargo build --tests -vv --features=c_avx512
    - name: binary tests
      working-directory: ./baokeshed_bin
      run: cargo test

  cross:
    name: cross test on mips
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: install cross
      run: cargo install cross
    - name: cross test
      run: cross test --target mips-unknown-linux-gnu --features=c_portable

  test_c_native:
    name: C implementation on Linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: cpuinfo
      run: cat /proc/cpuinfo

    # Again do a low-verosity test run first.
    - run: cargo test --release

    # The rerun-if-env-changed directives in build.rs mean that each of these
    # different CC settings will do a recompilation.
    - name: test native GCC
      env:
        CC: gcc
      run: cargo test -vv --features=c_native --release
    - name: test native Clang
      env:
        CC: clang
      run: cargo test -vv --features=c_native --release
